[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
description = """
Library to support the reading of epub files.
"""
documentation = "https://danigm.github.io/epub-rs-doc/epub/index.html"
exclude = ["test.epub"]
keywords = [
    "epub",
    "ebook",
]
license = "GPL-3.0"
name = "epub"
repository = "https://github.com/danigm/epub-rs.git"
version = "1.2.0"

[dependencies]
failure = "0.1.3"
regex = "1.0.5"
xml-rs = "0.8.0"
zip = "0.5.2"
percent-encoding = "1.0.1"
